/* This file is generated by yarn generate:api-contracts. Do not edit by hand. */

declare namespace ApiContractsInternal {
  export type Avatar = string
  export type Country = string | null
  export type Created = string
  export type CsrfToken = string
  export type Deleted = boolean
  export type Email = string
  export type Id = number
  export type ExternalId = string
  export type Provider = string
  export type IsAdmin = boolean
  export type LastLogin = string
  export type Name = string
  export type Providers = string[]
  export type Avatar1 = string
  export type Cover = string
  export type Created1 = string
  export type Id1 = number
  export type Slug = string
  export type Title = string
  export type Uuid = string
  export type Channels = ChannelCoreResponse[]
  export type Country1 = string | null
  export type Created2 = string
  export type Deleted1 = boolean
  export type Email1 = string
  export type Id2 = number
  export type IsAdmin1 = boolean
  export type LastLogin1 = string
  export type Name1 = string
  export type Providers1 = UserProviderResponse[]
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "AdminUsersResponse".
   */
  export type AdminUsersResponse = UserResponse[]
  export type Error = 'bad_request'
  export type Message = string | null
  export type Status = 400
  export type Cover1 = string
  export type Created3 = string
  export type Deleted2 = boolean
  export type Id3 = number
  export type Owner = number
  export type Ownername = string
  export type Pending = boolean
  export type Channel = number
  export type Created4 = string
  export type Deleted3 = boolean
  export type Id4 = number
  export type Created5 = string
  export type Deleted4 = boolean
  export type DescriptionUnsafe = string | null
  export type Id5 = number
  export type Main = boolean
  export type Pending1 = boolean
  export type Preview = string
  export type PrivateId = string
  export type Project = number
  export type ResourceDate = string
  export type Slug1 = string
  export type Src = string | null
  export type Title1 = string
  export type Type = string | null
  export type UpdatedAt = string
  export type Media = MediaResponse[]
  export type Pending2 = boolean
  export type Poster = string | null
  export type PosterColor = string | null
  export type ResourceDate1 = string
  export type Slug2 = string
  export type Subtitle = string | null
  export type Title2 = string
  export type UpdatedAt1 = string
  export type Projects = ProjectResponse[]
  export type Slug3 = string
  export type Title3 = string
  export type Uuid1 = string
  export type Created6 = string
  export type Deleted5 = boolean
  export type DescriptionUnsafe1 = string | null
  export type Id6 = number
  export type Main1 = boolean
  export type Pending3 = boolean
  export type Preview1 = string
  export type PrivateId1 = string
  export type Project1 = number
  export type ResourceDate2 = string
  export type Slug4 = string
  export type Src1 = string | null
  export type Title4 = string
  export type Type1 = string | null
  export type UpdatedAt2 = string
  export type Channel1 = number
  export type Created7 = string
  export type Deleted6 = boolean
  export type Id7 = number
  export type Media1 = MediaResponse[]
  export type Pending4 = boolean
  export type Poster1 = string | null
  export type PosterColor1 = string | null
  export type ResourceDate3 = string
  export type Slug5 = string
  export type Subtitle1 = string | null
  export type Title5 = string
  export type UpdatedAt3 = string
  export type Cover2 = string
  export type Created8 = string
  export type Deleted7 = boolean
  export type Id8 = number
  export type Owner1 = number
  export type Pending5 = boolean
  export type Slug6 = string
  export type Title6 = string
  export type Uuid2 = string
  export type Error1 = 'conflict'
  export type Message1 = string | null
  export type Status1 = 409
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "CoverType".
   */
  export type CoverType = 'profile' | 'new'
  export type Attempts = number
  export type Availableat = string
  export type Created9 = string
  export type Id9 = number
  export type Lasterror = string | null
  export type Payload =
    | ObjectsDeleteNamePayload
    | MediaProcessPayload
    | NotificationSendPayload
    | EmailSendPayload
    | DatabaseHardDeletePayload
  export type Name2 = string
  export type Objecttype = string
  export type Media2 = number
  export type Owner2 = number
  export type Source = string
  export type Description = string
  export type Event = string
  export type Htmlbody = string
  export type Subject = string
  export type Toemail = string
  export type Toname = string
  export type Entitytype = 'MEDIA' | 'PROJECT' | 'CHANNEL'
  export type Owner3 = number
  export type Reference = number
  export type Type2 = string
  export type Error2 = string
  export type Error3 = string
  export type Error4 = string
  export type Error5 = 'forbidden'
  export type Message2 = string | null
  export type Status2 = 403
  export type Error6 = string
  export type Message3 = string | null
  export type Status3 = number
  export type Status4 = string
  export type Error7 = 'internal_server_error'
  export type Message4 = string | null
  export type Status5 = 500
  export type Label = string | null
  export type Value = number | string
  export type Expiresat = string
  export type Src2 = string
  export type Token = string
  export type Description1 = string | null
  export type Main2 = boolean
  export type Resourcedate = string
  export type Description2 = string | null
  export type Filename = string
  export type Main3 = boolean
  export type Previewtype = 'frame' | 'new'
  export type Resourcedate1 = string
  export type Title7 = string
  export type Error8 = 'not_found'
  export type Message5 = string | null
  export type Status6 = 404
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "OAuthProvider".
   */
  export type OAuthProvider =
    | 'apple'
    | 'facebook'
    | 'github'
    | 'google'
    | 'microsoft'
    | 'yahoo'
    | 'test'
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "PosterType".
   */
  export type PosterType = 'default' | 'new'
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "PreviewType".
   */
  export type PreviewType = 'frame' | 'new'
  export type Cover3 = string
  export type Ownername1 = string
  export type Title8 = string
  export type Title9 = string
  export type Title10 = string
  export type Postercolor = string | null
  export type Postertype = 'default' | 'new'
  export type Subtitle2 = string | null
  export type Title11 = string | null
  export type Message6 = string | null
  export type Reported = boolean
  export type Mediaid = number
  export type Privateid = string
  export type Createdat = string
  export type Reason = string | null
  export type Reporter = string
  export type Reports = ReportedMediaReportResponse[]
  export type Title12 = string
  export type Createdat1 = string
  export type Reason1 = string | null
  export type Reporter1 = string
  export type Error9 = 'unauthorized'
  export type Message7 = string | null
  export type Status7 = 401
  export type Error10 = 'unprocessable_entity'
  export type Message8 = string | null
  export type Status8 = 422
  export type Reference1 = number
  export type Requiredresources = ('cover' | 'poster' | 'preview' | 'upload')[]
  export type Resourcetype = 'cover' | 'poster' | 'preview' | 'upload'
  export type Url = string
  export type Covertype = 'profile' | 'new'
  export type Title13 = string | null
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "UploadResourceType".
   */
  export type UploadResourceType = 'cover' | 'poster' | 'preview' | 'upload'
  export type Error11 = string
  export type Error12 = string
  export type Idle = boolean
  export type Jobsqueued = number
  export type Jobsrunning = number
  export type Outboxdelayed = number
  export type Outboxpending = number
  export type Outboxprocessing = number
  export type Outboxready = number

  export interface ApiContracts {
    AccountProfile: AccountProfileResponse
    AccountProvidersResponse: AccountProvidersResponse
    AdminUser: UserResponse
    AdminUsersResponse: AdminUsersResponse
    BadRequestErrorResponse: BadRequestErrorResponse
    ChannelDetail: ChannelDetailResponse
    ChannelMedia: MediaResponse1
    ChannelProject: ProjectResponse1
    ChannelSummary: ChannelSummaryResponse
    ConflictErrorResponse: ConflictErrorResponse
    CoverType: CoverType
    DeadLetterQueueItem: DeadLetterQueueItemResponse
    DeletionBlockedResponse: ErrorResponse
    ErrorDetailResponse: ErrorDetailResponse
    ErrorResponse: ErrorResponse1
    ForbiddenErrorResponse: ForbiddenErrorResponse
    GlobalHttpErrorResponse: GlobalHttpErrorResponse
    HealthResponse: HealthResponse
    InternalServerErrorResponse: InternalServerErrorResponse
    LabeledValue: LabeledValue
    MediaTokenResponse: MediaTokenResponse
    MediaUpdateRequest: MediaUpdateRequest
    MediaUploadPayload: MediaUploadPayload
    NotFoundErrorResponse: NotFoundErrorResponse
    OAuthProvider: OAuthProvider
    PosterType: PosterType
    PreviewType: PreviewType
    PrivateMediaChannel: PrivateMediaChannelResponse
    PrivateMediaProject: PrivateMediaProjectResponse1
    ProjectUploadPayload: ProjectUploadPayload
    ReportMediaResponse: ReportMediaResponse
    ReportedMediaItem: ReportedMediaItemResponse
    ReportedMediaReport: ReportedMediaReportResponse1
    UnauthorizedErrorResponse: UnauthorizedErrorResponse
    UnprocessableEntityErrorResponse: UnprocessableEntityErrorResponse
    UploadInstruction: UploadInstruction
    UploadMediaRequest: UploadMediaRequest
    UploadResourceType: UploadResourceType
    UploadStorageConflictResponse: ErrorDetailResponse1
    UploadValidationErrorResponse: ErrorDetailResponse2
    WorkerStatusResponse: WorkerStatusResponse
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "AccountProfile".
   */
  export interface AccountProfileResponse {
    avatar: Avatar
    country: Country
    created: Created
    csrf_token: CsrfToken
    deleted: Deleted
    email: Email
    id: Id
    identity_provider: UserProviderResponse | null
    is_admin: IsAdmin
    last_login: LastLogin
    name: Name
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "UserProviderResponse".
   */
  export interface UserProviderResponse {
    external_id: ExternalId
    provider: Provider
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "AccountProvidersResponse".
   */
  export interface AccountProvidersResponse {
    providers: Providers
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "AdminUser".
   */
  export interface UserResponse {
    avatar: Avatar1
    channels: Channels
    country: Country1
    created: Created2
    deleted: Deleted1
    email: Email1
    id: Id2
    is_admin: IsAdmin1
    last_login: LastLogin1
    name: Name1
    providers: Providers1
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ChannelCoreResponse".
   */
  export interface ChannelCoreResponse {
    cover: Cover
    created: Created1
    id: Id1
    slug: Slug
    title: Title
    uuid: Uuid
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "BadRequestErrorResponse".
   */
  export interface BadRequestErrorResponse {
    error: Error
    message?: Message
    status: Status
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ChannelDetail".
   */
  export interface ChannelDetailResponse {
    cover: Cover1
    created: Created3
    deleted?: Deleted2
    id: Id3
    owner: Owner
    ownername: Ownername
    pending?: Pending
    projects?: Projects
    slug: Slug3
    title: Title3
    uuid: Uuid1
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ProjectResponse".
   */
  export interface ProjectResponse {
    channel: Channel
    created: Created4
    deleted?: Deleted3
    id: Id4
    media?: Media
    pending?: Pending2
    poster: Poster
    poster_color: PosterColor
    resource_date: ResourceDate1
    slug: Slug2
    subtitle: Subtitle
    title: Title2
    updated_at: UpdatedAt1
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "MediaResponse".
   */
  export interface MediaResponse {
    created: Created5
    deleted?: Deleted4
    description_unsafe: DescriptionUnsafe
    id: Id5
    main: Main
    pending?: Pending1
    preview: Preview
    private_id: PrivateId
    project: Project
    resource_date: ResourceDate
    slug: Slug1
    src: Src
    title: Title1
    type: Type
    updated_at: UpdatedAt
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ChannelMedia".
   */
  export interface MediaResponse1 {
    created: Created6
    deleted?: Deleted5
    description_unsafe: DescriptionUnsafe1
    id: Id6
    main: Main1
    pending?: Pending3
    preview: Preview1
    private_id: PrivateId1
    project: Project1
    resource_date: ResourceDate2
    slug: Slug4
    src: Src1
    title: Title4
    type: Type1
    updated_at: UpdatedAt2
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ChannelProject".
   */
  export interface ProjectResponse1 {
    channel: Channel1
    created: Created7
    deleted?: Deleted6
    id: Id7
    media?: Media1
    pending?: Pending4
    poster: Poster1
    poster_color: PosterColor1
    resource_date: ResourceDate3
    slug: Slug5
    subtitle: Subtitle1
    title: Title5
    updated_at: UpdatedAt3
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ChannelSummary".
   */
  export interface ChannelSummaryResponse {
    cover: Cover2
    created: Created8
    deleted?: Deleted7
    id: Id8
    owner: Owner1
    pending?: Pending5
    slug: Slug6
    title: Title6
    uuid: Uuid2
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ConflictErrorResponse".
   */
  export interface ConflictErrorResponse {
    error: Error1
    message?: Message1
    status: Status1
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "DeadLetterQueueItem".
   */
  export interface DeadLetterQueueItemResponse {
    attempts: Attempts
    availableAt: Availableat
    created: Created9
    id: Id9
    lastError: Lasterror
    payload: Payload
    type: Type2
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ObjectsDeleteNamePayload".
   */
  export interface ObjectsDeleteNamePayload {
    name: Name2
    objectType: Objecttype
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "MediaProcessPayload".
   */
  export interface MediaProcessPayload {
    media: Media2
    owner: Owner2
    source: Source
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "NotificationSendPayload".
   */
  export interface NotificationSendPayload {
    description: Description
    event: Event
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "EmailSendPayload".
   */
  export interface EmailSendPayload {
    htmlBody: Htmlbody
    subject: Subject
    toEmail: Toemail
    toName: Toname
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "DatabaseHardDeletePayload".
   */
  export interface DatabaseHardDeletePayload {
    entityType: Entitytype
    owner: Owner3
    reference: Reference
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "DeletionBlockedResponse".
   */
  export interface ErrorResponse {
    error: Error2
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ErrorDetailResponse".
   */
  export interface ErrorDetailResponse {
    detail: Detail
    error: Error3
  }
  export interface Detail {
    [k: string]: unknown
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ErrorResponse".
   */
  export interface ErrorResponse1 {
    error: Error4
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ForbiddenErrorResponse".
   */
  export interface ForbiddenErrorResponse {
    error: Error5
    message?: Message2
    status: Status2
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "GlobalHttpErrorResponse".
   */
  export interface GlobalHttpErrorResponse {
    error: Error6
    message?: Message3
    status: Status3
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "HealthResponse".
   */
  export interface HealthResponse {
    status: Status4
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "InternalServerErrorResponse".
   */
  export interface InternalServerErrorResponse {
    error: Error7
    message?: Message4
    status: Status5
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "LabeledValue".
   */
  export interface LabeledValue {
    label?: Label
    value: Value
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "MediaTokenResponse".
   */
  export interface MediaTokenResponse {
    expiresAt: Expiresat
    src: Src2
    token: Token
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "MediaUpdateRequest".
   */
  export interface MediaUpdateRequest {
    description?: Description1
    main: Main2
    resourceDate: Resourcedate
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "MediaUploadPayload".
   */
  export interface MediaUploadPayload {
    description?: Description2
    filename: Filename
    main?: Main3
    previewType?: Previewtype
    resourceDate: Resourcedate1
    title: Title7
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "NotFoundErrorResponse".
   */
  export interface NotFoundErrorResponse {
    error: Error8
    message?: Message5
    status: Status6
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "PrivateMediaChannel".
   */
  export interface PrivateMediaChannelResponse {
    cover: Cover3
    ownername: Ownername1
    project: PrivateMediaProjectResponse
    title: Title9
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "PrivateMediaProjectResponse".
   */
  export interface PrivateMediaProjectResponse {
    media: MediaResponse
    title: Title8
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "PrivateMediaProject".
   */
  export interface PrivateMediaProjectResponse1 {
    media: MediaResponse
    title: Title10
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ProjectUploadPayload".
   */
  export interface ProjectUploadPayload {
    id: LabeledValue
    media: MediaUploadPayload
    posterColor?: Postercolor
    posterType?: Postertype
    subtitle?: Subtitle2
    title?: Title11
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ReportMediaResponse".
   */
  export interface ReportMediaResponse {
    message?: Message6
    reported: Reported
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ReportedMediaItem".
   */
  export interface ReportedMediaItemResponse {
    mediaId: Mediaid
    privateId: Privateid
    reports: Reports
    title: Title12
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ReportedMediaReportResponse".
   */
  export interface ReportedMediaReportResponse {
    createdAt: Createdat
    reason: Reason
    reporter: Reporter
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "ReportedMediaReport".
   */
  export interface ReportedMediaReportResponse1 {
    createdAt: Createdat1
    reason: Reason1
    reporter: Reporter1
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "UnauthorizedErrorResponse".
   */
  export interface UnauthorizedErrorResponse {
    error: Error9
    message?: Message7
    status: Status7
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "UnprocessableEntityErrorResponse".
   */
  export interface UnprocessableEntityErrorResponse {
    error: Error10
    message?: Message8
    status: Status8
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "UploadInstruction".
   */
  export interface UploadInstruction {
    reference: Reference1
    requiredResources?: Requiredresources
    resourceType: Resourcetype
    url: Url
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "UploadMediaRequest".
   */
  export interface UploadMediaRequest {
    coverType?: Covertype
    project: ProjectUploadPayload
    title?: Title13
    uuid: LabeledValue
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "UploadStorageConflictResponse".
   */
  export interface ErrorDetailResponse1 {
    detail: Detail1
    error: Error11
  }
  export interface Detail1 {
    [k: string]: unknown
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "UploadValidationErrorResponse".
   */
  export interface ErrorDetailResponse2 {
    detail: Detail2
    error: Error12
  }
  export interface Detail2 {
    [k: string]: unknown
  }
  /**
   * This interface was referenced by `ApiContracts`'s JSON-Schema
   * via the `definition` "WorkerStatusResponse".
   */
  export interface WorkerStatusResponse {
    idle: Idle
    jobsQueued: Jobsqueued
    jobsRunning: Jobsrunning
    outboxDelayed: Outboxdelayed
    outboxPending: Outboxpending
    outboxProcessing: Outboxprocessing
    outboxReady: Outboxready
  }
}
/* Clean public aliases for root backend contracts. */
export type ApiContracts = ApiContractsInternal.ApiContracts
export type AccountProfile = ApiContracts['AccountProfile']
export type AccountProvidersResponse = ApiContracts['AccountProvidersResponse']
export type AdminUser = ApiContracts['AdminUser']
export type AdminUsersResponse = ApiContracts['AdminUsersResponse']
export type BadRequestErrorResponse = ApiContracts['BadRequestErrorResponse']
export type ChannelDetail = ApiContracts['ChannelDetail']
export type ChannelMedia = ApiContracts['ChannelMedia']
export type ChannelProject = ApiContracts['ChannelProject']
export type ChannelSummary = ApiContracts['ChannelSummary']
export type ConflictErrorResponse = ApiContracts['ConflictErrorResponse']
export type CoverType = ApiContracts['CoverType']
export type DeadLetterQueueItem = ApiContracts['DeadLetterQueueItem']
export type DeletionBlockedResponse = ApiContracts['DeletionBlockedResponse']
export type ErrorDetailResponse = ApiContracts['ErrorDetailResponse']
export type ErrorResponse = ApiContracts['ErrorResponse']
export type ForbiddenErrorResponse = ApiContracts['ForbiddenErrorResponse']
export type GlobalHttpErrorResponse = ApiContracts['GlobalHttpErrorResponse']
export type HealthResponse = ApiContracts['HealthResponse']
export type InternalServerErrorResponse = ApiContracts['InternalServerErrorResponse']
export type LabeledValue = ApiContracts['LabeledValue']
export type MediaTokenResponse = ApiContracts['MediaTokenResponse']
export type MediaUpdateRequest = ApiContracts['MediaUpdateRequest']
export type MediaUploadPayload = ApiContracts['MediaUploadPayload']
export type NotFoundErrorResponse = ApiContracts['NotFoundErrorResponse']
export type OAuthProvider = ApiContracts['OAuthProvider']
export type PosterType = ApiContracts['PosterType']
export type PreviewType = ApiContracts['PreviewType']
export type PrivateMediaChannel = ApiContracts['PrivateMediaChannel']
export type PrivateMediaProject = ApiContracts['PrivateMediaProject']
export type ProjectUploadPayload = ApiContracts['ProjectUploadPayload']
export type ReportMediaResponse = ApiContracts['ReportMediaResponse']
export type ReportedMediaItem = ApiContracts['ReportedMediaItem']
export type ReportedMediaReport = ApiContracts['ReportedMediaReport']
export type UnauthorizedErrorResponse = ApiContracts['UnauthorizedErrorResponse']
export type UnprocessableEntityErrorResponse = ApiContracts['UnprocessableEntityErrorResponse']
export type UploadInstruction = ApiContracts['UploadInstruction']
export type UploadMediaRequest = ApiContracts['UploadMediaRequest']
export type UploadResourceType = ApiContracts['UploadResourceType']
export type UploadStorageConflictResponse = ApiContracts['UploadStorageConflictResponse']
export type UploadValidationErrorResponse = ApiContracts['UploadValidationErrorResponse']
export type WorkerStatusResponse = ApiContracts['WorkerStatusResponse']
