/* This file is generated by yarn generate:api-contracts. Do not edit by hand. */

export type Avatar = string
export type Country = string | null
export type Created = string
export type Csrftoken = string
export type Deleted = boolean
export type Email = string
export type Externalid = string
export type Provider = string
export type Isadmin = boolean
export type Lastlogin = string
export type Mediacount = number
export type Name = string
export type Newuser = boolean
export type AccountProvidersResponse = string[]
export type Avatar1 = string
export type Cover = string
export type Created1 = string
export type PublicID = string
export type Slug = string
export type Title = string
export type Channels = AdminChannelResponse[]
export type Country1 = string | null
export type Created2 = string
export type Deleted1 = boolean
export type Email1 = string
export type Isadmin1 = boolean
export type Lastlogin1 = string
export type Name1 = string
export type Newuser1 = boolean
export type Providers = UserProviderResponse[]
export type AdminUsersResponse = AdminUserResponse[]
export type Error = 'bad_request'
export type Message = string | null
export type Privatepath = string | null
export type Publicpath = string | null
export type Created3 = string
export type Deleted2 = boolean
export type Privatealbumpath = string | null
export type Privatepath1 = string | null
export type Publicpath1 = string | null
export type Created4 = string
export type Deleted3 = boolean
export type Descriptionunsafe = string | null
export type Main = boolean
export type Orientation = 'landscape' | 'portrait'
export type Pending = boolean
export type Preview = string
export type PrivateID = string
export type PublicID1 = string
export type Resourcedate = string
export type Slug1 = string
export type Src = string | null
export type Title1 = string
export type Type = string | null
export type Updatedat = string
export type Media = MediaResponse[]
export type Pending1 = boolean
export type Poster = string | null
export type Postercolor = string | null
export type PrivateID1 = string
export type PublicID2 = string
export type Resourcedate1 = string
export type Slug2 = string
export type Subtitle = string | null
export type Title2 = string
export type Updatedat1 = string
export type Created5 = string
export type Deleted4 = boolean
export type Media1 = MediaResponse[]
export type Pending2 = boolean
export type Poster1 = string | null
export type Postercolor1 = string | null
export type PrivateID2 = string
export type PublicID3 = string
export type Resourcedate2 = string
export type Slug3 = string
export type Subtitle1 = string | null
export type Title3 = string
export type Updatedat2 = string
export type Albums = AlbumResponse1[]
export type Publicpath2 = string | null
export type Cover1 = string
export type Created6 = string
export type Deleted5 = boolean
export type Ownername = string
export type Pending3 = boolean
export type PublicID4 = string
export type Slug4 = string
export type Title4 = string
export type HistoryResourceID = string
export type Type1 = 'channel' | 'privateMedia' | 'privateAlbum'
export type Deleteditems = HistoryDeletedItemResponse[]
export type Cover2 = string | null
export type HistoryResourceID1 = string
export type Slug5 = string | null
export type Title5 = string
export type Type2 = 'channel' | 'privateMedia' | 'privateAlbum'
export type Items = HistoryItemResponse[]
export type HistoryResourceID2 = string
export type Type3 = 'channel' | 'privateMedia' | 'privateAlbum'
export type Persisteditems = HistoryItemRequest[]
export type Created7 = string
export type Deleted6 = boolean
export type Descriptionunsafe1 = string | null
export type Main1 = boolean
export type Orientation1 = 'landscape' | 'portrait'
export type Pending4 = boolean
export type Preview1 = string
export type PrivateID3 = string
export type PublicID5 = string
export type Resourcedate3 = string
export type Slug6 = string
export type Src1 = string | null
export type Title6 = string
export type Type4 = string | null
export type Updatedat3 = string
export type Cover3 = string
export type Created8 = string
export type Deleted7 = boolean
export type Pending5 = boolean
export type PublicID6 = string
export type Slug7 = string
export type Title7 = string
export type Error1 = 'conflict'
export type Message1 = string | null
export type CoverMode = 'profile' | 'upload'
export type Error2 = string
export type Error3 = string
export type Error4 = string
export type Error5 = 'forbidden'
export type Message2 = string | null
export type Error6 = string
export type Message3 = string | null
export type Status = string
export type Error7 = 'internal_server_error'
export type Message4 = string | null
export type Description = string | null
export type Main2 = boolean
export type Resourcedate4 = string
export type Title8 = string
export type Description1 = string | null
export type Filename = string | null
export type Main3 = boolean
export type Mode = 'frame' | 'upload'
export type Resourcedate5 = string
export type Title9 = string | null
export type Error8 = 'not_found'
export type Message5 = string | null
export type OAuthProvider =
  | 'apple'
  | 'facebook'
  | 'github'
  | 'google'
  | 'microsoft'
  | 'yahoo'
  | 'test'
export type PosterMode = 'color' | 'upload'
export type PreviewMode = 'frame' | 'upload'
export type Created9 = string | null
export type Descriptionunsafe2 = string | null
export type Orientation2 = ('landscape' | 'portrait') | null
export type Preview2 = string | null
export type PrivateID4 = string
export type Resourcedate6 = string | null
export type Slug8 = string
export type Src2 = string | null
export type Title10 = string
export type Type5 = string | null
export type Updatedat4 = string | null
export type Media2 = PrivateMediaItemResponse[]
export type Poster2 = string | null
export type Postercolor2 = string | null
export type PrivateID5 = string | null
export type Media3 = PrivateMediaItemResponse[]
export type Poster3 = string | null
export type Postercolor3 = string | null
export type PrivateID6 = string | null
export type Cover4 = string
export type Ownername1 = string
export type Message6 = string | null
export type Reported = boolean
export type PrivateID7 = string
export type PublicID7 = string
export type Createdat = string
export type Reason = string | null
export type Reporter = string
export type Reports = ReportedMediaReportResponse[]
export type Slug9 = string
export type Title11 = string
export type Createdat1 = string
export type Reason1 = string | null
export type Reporter1 = string
export type Error9 = 'unauthorized'
export type Message7 = string | null
export type Error10 = 'unprocessable_entity'
export type Message8 = string | null
export type Cover5 = boolean
export type Poster4 = boolean
export type Preview3 = boolean
export type Upload = boolean
export type Reference = string
export type Requiredresources = ('cover' | 'poster' | 'preview' | 'upload')[]
export type Resourcetype = 'cover' | 'poster' | 'preview' | 'upload'
export type Url = string
export type Album = ExistingAlbumSelection | CreateAlbumSelection | UnselectedAlbumSelection
export type Mode1 = 'existing'
export type Privateid = string
export type Mode2 = 'create'
export type Color = string | null
export type Mode3 = 'color' | 'upload'
export type Subtitle2 = string | null
export type Title12 = string | null
export type Mode4 = 'unselected'
export type Channel = ExistingChannelSelection | CreateChannelSelection | UnselectedChannelSelection
export type Mode5 = 'existing'
export type PublicID8 = string
export type Mode6 = 'profile' | 'upload'
export type Mode7 = 'create'
export type Title13 = string | null
export type Mode8 = 'unselected'
export type Idempotencykey = string | null
export type UploadResourceType = 'cover' | 'poster' | 'preview' | 'upload'
export type Error11 = string
export type Error12 = string
export type Blockers = string[]
export type Cansubmit = boolean
export type Idle = boolean
export type Jobsqueued = number
export type Jobsrunning = number

export interface ApiContracts {
  AccountProfile: AccountProfileResponse
  AccountProvidersResponse: AccountProvidersResponse
  AdminUser: AdminUserResponse
  AdminUsersResponse: AdminUsersResponse
  BadRequestErrorResponse: BadRequestErrorResponse
  ChannelAlbum: AlbumResponse
  ChannelDetail: ChannelDetailResponse
  ChannelHistory: HistoryResponse
  ChannelMedia: MediaResponse1
  ChannelSummary: ChannelSummaryResponse
  ConflictErrorResponse: ConflictErrorResponse
  CoverMode: CoverMode
  DeletionBlockedResponse: ErrorResponse
  ErrorDetailResponse: ErrorDetailResponse
  ErrorResponse: ErrorResponse1
  ForbiddenErrorResponse: ForbiddenErrorResponse
  GlobalHttpErrorResponse: GlobalHttpErrorResponse
  HealthResponse: HealthResponse
  InternalServerErrorResponse: InternalServerErrorResponse
  MediaUpdateRequest: MediaUpdateRequest
  MediaUploadPayload: MediaUploadPayload
  NotFoundErrorResponse: NotFoundErrorResponse
  OAuthProvider: OAuthProvider
  PosterMode: PosterMode
  PreviewMode: PreviewMode
  PrivateMediaAlbum: PrivateMediaAlbumResponse
  PrivateMediaChannel: PrivateMediaChannelResponse
  ReportMediaResponse: ReportMediaResponse
  ReportedMediaItem: ReportedMediaItemResponse
  ReportedMediaReport: ReportedMediaReportResponse1
  UnauthorizedErrorResponse: UnauthorizedErrorResponse
  UnprocessableEntityErrorResponse: UnprocessableEntityErrorResponse
  UploadDraftFiles: UploadDraftFiles
  UploadInstruction: UploadInstruction
  UploadMediaRequest: UploadMediaRequest
  UploadResourceType: UploadResourceType
  UploadStorageConflictResponse: ErrorDetailResponse1
  UploadValidationErrorResponse: ErrorDetailResponse2
  UploadValidationResponse: UploadValidationResponse
  WorkerStatusResponse: WorkerStatusResponse
}
export interface AccountProfileResponse {
  avatar: Avatar
  country: Country
  created: Created
  csrfToken: Csrftoken
  deleted: Deleted
  email: Email
  identityProvider: UserProviderResponse | null
  isAdmin: Isadmin
  lastLogin: Lastlogin
  mediaCount?: Mediacount
  name: Name
  newUser: Newuser
}
export interface UserProviderResponse {
  externalId: Externalid
  provider: Provider
}
export interface AdminUserResponse {
  avatar: Avatar1
  channels: Channels
  country: Country1
  created: Created2
  deleted: Deleted1
  email: Email1
  isAdmin: Isadmin1
  lastLogin: Lastlogin1
  name: Name1
  newUser: Newuser1
  providers: Providers
}
export interface AdminChannelResponse {
  cover: Cover
  created: Created1
  publicId: PublicID
  slug: Slug
  title: Title
}
export interface BadRequestErrorResponse {
  detail?: unknown
  error: Error
  message?: Message
}
export interface AlbumResponse {
  canonicalPath?: AlbumCanonicalPathResponse | null
  created: Created3
  deleted?: Deleted2
  media?: Media
  pending?: Pending1
  poster: Poster
  posterColor: Postercolor
  privateId: PrivateID1
  publicId: PublicID2
  resourceDate: Resourcedate1
  slug: Slug2
  subtitle: Subtitle
  title: Title2
  updatedAt: Updatedat1
  [k: string]: unknown
}
export interface AlbumCanonicalPathResponse {
  privatePath?: Privatepath
  publicPath?: Publicpath
}
export interface MediaResponse {
  canonicalPath?: MediaCanonicalPathResponse | null
  created: Created4
  deleted?: Deleted3
  descriptionUnsafe: Descriptionunsafe
  main: Main
  orientation: Orientation
  pending?: Pending
  preview: Preview
  privateId: PrivateID
  publicId: PublicID1
  resourceDate: Resourcedate
  slug: Slug1
  src: Src
  title: Title1
  type: Type
  updatedAt: Updatedat
  [k: string]: unknown
}
export interface MediaCanonicalPathResponse {
  privateAlbumPath?: Privatealbumpath
  privatePath?: Privatepath1
  publicPath?: Publicpath1
}
export interface ChannelDetailResponse {
  albums?: Albums
  canonicalPath?: ChannelCanonicalPathResponse | null
  cover: Cover1
  created: Created6
  deleted?: Deleted5
  ownerName: Ownername
  pending?: Pending3
  publicId: PublicID4
  slug: Slug4
  title: Title4
  [k: string]: unknown
}
export interface AlbumResponse1 {
  canonicalPath?: AlbumCanonicalPathResponse | null
  created: Created5
  deleted?: Deleted4
  media?: Media1
  pending?: Pending2
  poster: Poster1
  posterColor: Postercolor1
  privateId: PrivateID2
  publicId: PublicID3
  resourceDate: Resourcedate2
  slug: Slug3
  subtitle: Subtitle1
  title: Title3
  updatedAt: Updatedat2
  [k: string]: unknown
}
export interface ChannelCanonicalPathResponse {
  publicPath?: Publicpath2
}
export interface HistoryResponse {
  deletedItems?: Deleteditems
  items: Items
  persistedItems?: Persisteditems
}
export interface HistoryDeletedItemResponse {
  resourceId: HistoryResourceID
  type: Type1
}
export interface HistoryItemResponse {
  cover?: Cover2
  resourceId: HistoryResourceID1
  slug?: Slug5
  title: Title5
  type: Type2
}
export interface HistoryItemRequest {
  resourceId: HistoryResourceID2
  type: Type3
}
export interface MediaResponse1 {
  canonicalPath?: MediaCanonicalPathResponse | null
  created: Created7
  deleted?: Deleted6
  descriptionUnsafe: Descriptionunsafe1
  main: Main1
  orientation: Orientation1
  pending?: Pending4
  preview: Preview1
  privateId: PrivateID3
  publicId: PublicID5
  resourceDate: Resourcedate3
  slug: Slug6
  src: Src1
  title: Title6
  type: Type4
  updatedAt: Updatedat3
  [k: string]: unknown
}
export interface ChannelSummaryResponse {
  canonicalPath?: ChannelCanonicalPathResponse | null
  cover: Cover3
  created: Created8
  deleted?: Deleted7
  pending?: Pending5
  publicId: PublicID6
  slug: Slug7
  title: Title7
  [k: string]: unknown
}
export interface ConflictErrorResponse {
  detail?: unknown
  error: Error1
  message?: Message1
}
export interface ErrorResponse {
  error: Error2
}
export interface ErrorDetailResponse {
  detail: Detail2
  error: Error3
}
export interface Detail2 {
  [k: string]: unknown
}
export interface ErrorResponse1 {
  error: Error4
}
export interface ForbiddenErrorResponse {
  detail?: unknown
  error: Error5
  message?: Message2
}
export interface GlobalHttpErrorResponse {
  detail?: unknown
  error: Error6
  message?: Message3
}
export interface HealthResponse {
  status: Status
}
export interface InternalServerErrorResponse {
  detail?: unknown
  error: Error7
  message?: Message4
}
export interface MediaUpdateRequest {
  description?: Description
  main: Main2
  resourceDate: Resourcedate4
  title: Title8
}
export interface MediaUploadPayload {
  description?: Description1
  filename?: Filename
  main?: Main3
  preview: MediaPreviewSelection
  resourceDate: Resourcedate5
  title?: Title9
}
export interface MediaPreviewSelection {
  mode: Mode
}
export interface NotFoundErrorResponse {
  detail?: unknown
  error: Error8
  message?: Message5
}
export interface PrivateMediaAlbumResponse {
  media?: Media2
  poster?: Poster2
  posterColor?: Postercolor2
  privateId?: PrivateID5
}
export interface PrivateMediaItemResponse {
  created?: Created9
  descriptionUnsafe: Descriptionunsafe2
  orientation?: Orientation2
  preview?: Preview2
  privateId: PrivateID4
  resourceDate?: Resourcedate6
  slug: Slug8
  src?: Src2
  title: Title10
  type?: Type5
  updatedAt?: Updatedat4
}
export interface PrivateMediaChannelResponse {
  album: PrivateMediaAlbumResponse1
  canonicalPath?: MediaCanonicalPathResponse | null
  cover: Cover4
  ownerName: Ownername1
}
export interface PrivateMediaAlbumResponse1 {
  media?: Media3
  poster?: Poster3
  posterColor?: Postercolor3
  privateId?: PrivateID6
}
export interface ReportMediaResponse {
  message?: Message6
  reported: Reported
}
export interface ReportedMediaItemResponse {
  privateId: PrivateID7
  publicId: PublicID7
  reports: Reports
  slug: Slug9
  title: Title11
}
export interface ReportedMediaReportResponse {
  createdAt: Createdat
  reason: Reason
  reporter: Reporter
}
export interface ReportedMediaReportResponse1 {
  createdAt: Createdat1
  reason: Reason1
  reporter: Reporter1
}
export interface UnauthorizedErrorResponse {
  detail?: unknown
  error: Error9
  message?: Message7
}
export interface UnprocessableEntityErrorResponse {
  detail?: unknown
  error: Error10
  message?: Message8
}
export interface UploadDraftFiles {
  cover?: Cover5
  poster?: Poster4
  preview?: Preview3
  upload?: Upload
}
export interface UploadInstruction {
  reference: Reference
  requiredResources?: Requiredresources
  resourceType: Resourcetype
  url: Url
}
export interface UploadMediaRequest {
  album: Album
  channel: Channel
  files?: UploadDraftFiles | null
  idempotencyKey?: Idempotencykey
  media: MediaUploadPayload
}
export interface ExistingAlbumSelection {
  mode: Mode1
  privateId: Privateid
}
export interface CreateAlbumSelection {
  mode: Mode2
  poster: AlbumCreatePoster
  subtitle?: Subtitle2
  title?: Title12
}
export interface AlbumCreatePoster {
  color?: Color
  mode: Mode3
}
export interface UnselectedAlbumSelection {
  mode: Mode4
}
export interface ExistingChannelSelection {
  mode: Mode5
  publicId: PublicID8
}
export interface CreateChannelSelection {
  cover: ChannelCreateCover
  mode: Mode7
  title?: Title13
}
export interface ChannelCreateCover {
  mode: Mode6
}
export interface UnselectedChannelSelection {
  mode: Mode8
}
export interface ErrorDetailResponse1 {
  detail: Detail9
  error: Error11
}
export interface Detail9 {
  [k: string]: unknown
}
export interface ErrorDetailResponse2 {
  detail: Detail10
  error: Error12
}
export interface Detail10 {
  [k: string]: unknown
}
export interface UploadValidationResponse {
  blockers: Blockers
  canSubmit: Cansubmit
  requiredFiles: UploadDraftFiles
}
export interface WorkerStatusResponse {
  idle: Idle
  jobsQueued: Jobsqueued
  jobsRunning: Jobsrunning
}
